### ISSUE TITLE
Fix cafe/urls.py to avoid hard coding urls.

### ISSUE THREAD

**Issue by sjyk** [BerkeleyAutomation/malasakit-v1#1]
E.g "urlpatterns = [
    url(r'^v21/', include('pcari.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^pcari/', include('pcari.urls')),
]"

Remove these patterns and always reference the root.

**Comment by sjyk** [comment]
Also fix the corresponding settings.py
URL_ROOT = 'http://opinion.berkeley.edu/pcari'
STATIC_URL = URL_ROOT + '/static/'

**Comment by liboan** [comment]
Trying to clarify- do you want the landing page to appear at the root, instead of having to go to either /v21/ or /pcari/?

**Comment by sjyk** [comment]
Yes, make it the root /, we should have a variable in settings that allows us to get the full URL.

**Comment by jonathan-j-lee** [comment]
Addressed in #34.
