### ISSUE TITLE
Added PyPI dependencies to requirements.txt

### ISSUE THREAD

**Issue by liboan** [BerkeleyAutomation/malasakit-v1#14]
I've seen this done in some places- we can put all the package dependencies into a file and end-users can run `pip install requirements.txt` 
Makes it easier if we end up juggling multiple dependencies and want specific versions for each.

https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by jonathan-j-lee** [comment]
Addressed in #35.
