### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#18]
Add a 404 page or 404 redirect for invalid GET requests

**Comment by jonathan-j-lee** [comment]
Addressed in https://github.com/BerkeleyAutomation/malasakit-v1/commit/631ffcb59db45fd3ddee0521704b141122ca72f8. Will close once the changes are in master.

**Comment by jonathan-j-lee** [comment]
Addressed in #61.
