### ISSUE TITLE
Switching Language Bug

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#25]
While writing text on the last part of the survey (http://opinion.berkeley.edu/pcari-test/comment/), switching languages also deletes all user input from the text box.

**Comment by jonathan-j-lee** [comment]
Almost certain this has been fixed, but more testing required.

**Comment by jonathan-j-lee** [comment]
Switching language no longer deletes user input (tried this on the production server). I think we can close this now. @liboan: please implement a test for this.
