### ISSUE TITLE
Changing languages doesn't always work (see comments)

### ISSUE THREAD

**Issue by sequoia-tree** [BerkeleyAutomation/malasakit-v1#27]
From the google doc:

* First load the site (in English). Then click the “menu” circle in the upper right. Then, in the menu, switch language to Filipino. Now click “back” in the upper right. For some reason it doesn’t work, and you have to click it again. (I double checked that without switching languages, it takes only 1 click.) The same problem occurs if you load it in Filipino and copy the process above, but switch to English.

* When you are writing your own idea in the text box, there are a few issues with switching languages. It was loaded in Filipino, and I clicked “menu”. It took 2 clicks to switch languages to English, and it took 3 for “back” to work. Once I did get back to the page with the text box, the language reset back to Filipino. (Notably, when I clicked “menu” again, that page was still in English). Then, switching to English on the main page also makes the menu switch back to Filipino...

**Comment by jonathan-j-lee** [comment]
Closing for duplicating #25.
