### ISSUE TITLE
"Idea spheres" seem arbitrary to users & sometimes become hidden under other spheres

### ISSUE THREAD

**Issue by sequoia-tree** [BerkeleyAutomation/malasakit-v1#28]

**Comment by JustinMi** [comment]
Remove idea spheres completely

**Comment by jonathan-j-lee** [comment]
I'm reopening this because the bloom page is still a possibility.

**Comment by jonathan-j-lee** [comment]
Addressed in #74. Comment icons are not displaying in Andrew's browser, need further testing.
