### ISSUE TITLE
Support editing a previous answer without refilling the entire form

### ISSUE THREAD

**Issue by sequoia-tree** [BerkeleyAutomation/malasakit-v1#31]
Users want to change answer in one of the questions (upon seeing it in the review page), presses back until desired question number, then answers, but is frustrated that he/she has to answer all of the other questions again

**Comment by sequoia-tree** [comment]
Also backspace (or the keyboard shortcut for "back") causes issues in Safari, Chrome, presumably others.

**Comment by sequoia-tree** [comment]
Users want to change answer in one of the questions (upon seeing it in the review page), presses back until desired question number, then answers, but is frustrated that he/she has to answer all of the other questions again

**Comment by jonathan-j-lee** [comment]
This issue is a combination of three separate issues, two of which are duplicates of #21 and #29. I've edited this issue so that it only covers the answer editing issue.

**Comment by jonathan-j-lee** [comment]
Duplicate of #55, which is better formulated than this issue.
