### ISSUE TITLE
Fix style to comply with PEP 8

### ISSUE THREAD

**Issue by jonathan-j-lee** [BerkeleyAutomation/malasakit-v1#38]
Much of `views.py` appears to use tabs, rather than the four spaces recommended by [PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces). All existing (and future) code should transition to the use of spaces for indentation.

**Comment by JustinMi** [comment]
For those who use Sublime 3, do you know how to convert tabs to spaces? I tried following the instructions in [this](https://www.sublimetext.com/docs/3/indentation.html) but the linter still complains.

**Comment by JustinMi** [comment]
also, fix whitespace #41

**Comment by jonathan-j-lee** [comment]
I'm reopening this because not all files are targeted by the linter yet. Will close this once that happens.

**Comment by jonathan-j-lee** [comment]
Addressed in #61.
