### ISSUE TITLE
App crashes when user enters letters in the "Age" text box

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#47]
![image](https://cloud.githubusercontent.com/assets/10902110/26610051/0c566a0a-455a-11e7-89e6-c0e15165a466.png)
When user submits, the app crashes:
![image](https://cloud.githubusercontent.com/assets/10902110/26610063/168d6ce4-455a-11e7-910f-302e6323388a.png)

We need to implement proper error handling.

**Comment by liboan** [comment]
I think someone (Jonathan?) mentioned Django had form validation or
something, sounds like it would be good for this situation

**Comment by JustinMi** [comment]
#40

**Comment by jonathan-j-lee** [comment]
Addressed fully in #56 -- the input element has the attribute `type="number"`, so it is impossible to submit non-numerical characters.
