### ISSUE TITLE
Add admin functionality to delete empty comments

### ISSUE THREAD

**Issue by jonathan-j-lee** [BerkeleyAutomation/malasakit-v1#49]
This would ensure the dataset is clean and that users are guaranteed to be presented with an actual comment.

**Comment by JustinMi** [comment]
Can we confirm that we are doing this? This issue was brought up a while ago, just want to be sure that we are still doing this.

**Comment by JustinMi** [comment]
whoops, closed by accident

**Comment by jonathan-j-lee** [comment]
By using word count to filter for empty comments, an administrator can select all comments included in the query and delete them from the panel.

**Comment by jonathan-j-lee** [comment]
Per team discussion, the database should be strictly insert-only. Closing this for that reason.
