### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by sjyk** [BerkeleyAutomation/malasakit-v1#7]
Write unit tests for all of the views. This means generating post requests with data and testing to see if the data is stored properly.

**Comment by jonathan-j-lee** [comment]
Update: this was already done to some extent, but thorough test cases (especially those invoking various failure modes) would be ideal. Follow the `unit-test` branch for updates.

**Comment by jonathan-j-lee** [comment]
Addressed in #105 and #107.
