### ISSUE TITLE
Serve site over HTTPS

### ISSUE THREAD

**Issue by jonathan-j-lee** [BerkeleyAutomation/malasakit-v1#81]
[Service workers will not register without HTTPS, for security reasons.](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Custom_responses_to_requests)

**Comment by jonathan-j-lee** [comment]
Now addressed. @JustinMi: will need to resolve automatically renewing the certificate.

**Comment by JustinMi** [comment]
@jonathan-j-lee: I created a chron job--will check if it works in the coming month or two
