### ISSUE TITLE
Add writeup of design changes, etc. in Wiki

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#83]
- [ ] MySQL vs SQLite

**Comment by jonathan-j-lee** [comment]
Wiki documentation is pretty much complete. The particular change you brought up (MySQL vs. SQLite) is discussed [on the models page](https://github.com/BerkeleyAutomation/malasakit-v1/wiki/Models#choosing-a-database-implementation).
