### ISSUE TITLE
Alternative UI for the peer responses page

### ISSUE THREAD

**Issue by jonathan-j-lee** [BerkeleyAutomation/malasakit-v1#89]

**Comment by sequoia-tree** [comment]
Include left and right end text, too.
Make it clear why they're all on a numerical scale, or change that.

**Comment by sequoia-tree** [comment]
Summary page
Joyce - Add spacings or borders or separation cues between the analysis and the next question.
Joyce - I suggest that the question should be more emphasized than the text “For the question”

**Comment by jonathan-j-lee** [comment]
Addressed in #106.
