### ISSUE TITLE
Landing page (google doc suggestions)

### ISSUE THREAD

**Issue by sequoia-tree** [BerkeleyAutomation/malasakit-v1#99]
Landing page (collated by Nathaniel): 
- [x] When using desktop computers, entire page does not fit in one screen (user needs to scroll down to see the text at the bottom)
Resolution: 1366 x 768
- [x] ~~“Begin” can be all caps~~ [Will not be implemented]
- [x] Acknowledgement at the bottom to include NU: A project by the CITRIS Connected Communities Initiative at UC Berkeley, and National University,

**Comment by jonathan-j-lee** [comment]
All of these have been addressed by #106.
